### ISSUE TITLE
Declaration of readHumidity in bme280.h

### ISSUE THREAD

**Issue by Incruen** [Sylaina/bme280#2]
Hi!

In file bme280.h there may be a problem with line 143, because you wrote "bme280_readHumidit**iy**". Atmel Studio shows me a warning about this (implicit declaration of function..."

Jorge

**Comment by swklemmer** [comment]
Hola Jorge,
Me parece muy nada que ver tu comentario.
Gracias,

Chao.

**Comment by Incruen** [comment]
Jajajajjaj buena foto

**Comment by Sylaina** [comment]
fixed
