### ISSUE TITLE
Can't initialize the sensor.

### ISSUE THREAD

**Issue by colesnicov** [Sylaina/bme280#3]
Good day. I can't read the values from the sensor. I'm using your example, the only thing I changed was the I2C address for the sensor. I2C_Error_code returns '24'. But Adafruit_BME280 necessary information from the sensor yet, but I want Arduino, pure C is better.Vedel would you do with it?

**Comment by Sylaina** [comment]
Error-Code 24 means you don't receive ACK and NACK at I2C. Check wiring for sensor or/and I2C-Address. BME280 use typical 0x77 or 0x76 as I2C address, depended at SDO-Pin from BME280.

Be careful, I changed I2C adress-handling today, with actual lib you have just define logic level of SDO-pin (default: 1, means high level, I2C address will be assumed at 0x77).
