### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mdmrm** [Sylaina/bme280#4]
Hi,
I try compile this project and I have the error
pls see the log

"**** Build of configuration Release for project TEST_BME ****

make all 
'Building file: ../main.c'
'Invoking: AVR Compiler'
avr-gcc -Wall -Os -fpack-struct -fshort-enums -ffunction-sections -fdata-sections -std=gnu99 -funsigned-char -funsigned-bitfields -mmcu=atmega328p -DF_CPU=11059200UL -MMD -MP -MF"main.d" -MT"main.d" -c -o "main.o" "../main.c"
../main.c: In function 'main':
../main.c:14:3: error: too few arguments to function 'bme280_init'
../bme280.h:133:9: note: declared here
../main.c:16:3: error: too few arguments to function 'bme280_readTemperature'
../bme280.h:135:7: note: declared here
../main.c:17:3: error: too few arguments to function 'bme280_readPressure'
../bme280.h:136:7: note: declared here
../main.c:18:3: error: too few arguments to function 'bme280_readHumidity'
../bme280.h:137:7: note: declared here
../main.c:11:9: warning: variable 'humidity' set but not used [-Wunused-but-set-variable]
../main.c:10:9: warning: variable 'pressure' set but not used [-Wunused-but-set-variable]
../main.c:9:9: warning: variable 'temperature' set but not used [-Wunused-but-set-variable]
make: *** [main.o] Error 1

**** Build Finished ****

you can help me fix the problem?
best regards

**Comment by mdmrm** [comment]
ok, the previous post the bug is mine :)
in bme280.c
"Purpose: Initialise sensor
  Input Parameter: sensor
  Return Value: uint8_t
 - Value 0x00 means BME280 detected
 - Value 0x01 means BMP280 detected
 - Value 0xff means sensor unknown or argue out of range"

and  in main.c
.....
  // init sensor
  bme280_init(0);
  // read values
  temperature = bme280_readTemperature(0); // in °C
....

and during compilation
**** Build of configuration Release for project TEST_BME ****

make all 
'Building file: ../main.c'
'Invoking: AVR Compiler'
avr-gcc -Wall -Os -fpack-struct -fshort-enums -ffunction-sections -fdata-sections -std=gnu99 -funsigned-char -funsigned-bitfields -mmcu=atmega328p -DF_CPU=11059200UL -MMD -MP -MF"main.d" -MT"main.d" -c -o "main.o" "../main.c"
'Finished building: ../main.c'
' '
'Building target: TEST_BME.elf'
'Invoking: AVR C Linker'
avr-gcc -Wl,-Map,TEST_BME.map -mmcu=atmega328p -o "TEST_BME.elf"  ./bme280.o ./i2c.o ./main.o   
c:/program files/atmel/avr tools/avr toolchain/bin/../lib/gcc/avr/4.6.2/../../../../avr/lib/avr5\libc.a(pow.o):/home/tools/hudson/workspace/avr8-gnu-toolchain/src/avr-libc/libm/fplib/pow.S:214:(.text.avr-libc.fplib+0x94): relocation truncated to fit: R_AVR_13_PCREL against symbol `__mulsf3' defined in .text section in c:/program files/atmel/avr tools/avr toolchain/bin/../lib/gcc/avr/4.6.2/avr5\libgcc.a(_mul_sf.o)
c:/program files/atmel/avr tools/avr toolchain/bin/../lib/gcc/avr/4.6.2/../../../../avr/lib/avr5\libc.a(inverse.o):/home/tools/hudson/workspace/avr8-gnu-toolchain/src/avr-libc/libm/fplib/inverse.S:50:(.text.avr-libc.fplib+0xc): relocation truncated to fit: R_AVR_13_PCREL against symbol `__divsf3' defined in .text section in c:/program files/atmel/avr tools/avr toolchain/bin/../lib/gcc/avr/4.6.2/avr5\libgcc.a(_div_sf.o)
c:/program files/atmel/avr tools/avr toolchain/bin/../lib/gcc/avr/4.6.2/../../../../avr/lib/avr5\libc.a(log.o):/home/tools/hudson/workspace/avr8-gnu-toolchain/src/avr-libc/libm/fplib/log.S:96:(.text.avr-libc.fplib+0x46): relocation truncated to fit: R_AVR_13_PCREL against symbol `__addsf3' defined in .text section in c:/program files/atmel/avr tools/avr toolchain/bin/../lib/gcc/avr/4.6.2/avr5\libgcc.a(_addsub_sf.o)
c:/program files/atmel/avr tools/avr toolchain/bin/../lib/gcc/avr/4.6.2/../../../../avr/lib/avr5\libc.a(log.o):/home/tools/hudson/workspace/avr8-gnu-toolchain/src/avr-libc/libm/fplib/log.S:100:(.text.avr-libc.fplib+0x4e): relocation truncated to fit: R_AVR_13_PCREL against symbol `__addsf3' defined in .text section in c:/program files/atmel/avr tools/avr toolchain/bin/../lib/gcc/avr/4.6.2/avr5\libgcc.a(_addsub_sf.o)
c:/program files/atmel/avr tools/avr toolchain/bin/../lib/gcc/avr/4.6.2/../../../../avr/lib/avr5\libc.a(log.o):/home/tools/hudson/workspace/avr8-gnu-toolchain/src/avr-libc/libm/fplib/log.S:116:(.text.avr-libc.fplib+0x6a): relocation truncated to fit: R_AVR_13_PCREL against symbol `__floatsisf' defined in .text section in c:/program files/atmel/avr tools/avr toolchain/bin/../lib/gcc/avr/4.6.2/avr5\libgcc.a(_si_to_sf.o)
c:/program files/atmel/avr tools/avr toolchain/bin/../lib/gcc/avr/4.6.2/../../../../avr/lib/avr5\libc.a(modf.o):/home/tools/hudson/workspace/avr8-gnu-toolchain/src/avr-libc/libm/fplib/modf.S:90:(.text.avr-libc.fplib+0x3e): relocation truncated to fit: R_AVR_13_PCREL against symbol `__subsf3' defined in .text section in c:/program files/atmel/avr tools/avr toolchain/bin/../lib/gcc/avr/4.6.2/avr5\libgcc.a(_addsub_sf.o)
collect2: ld returned 1 exit status
make: *** [TEST_BME.elf] Error 1

**** Build Finished ****

you can help me fix the problem?
best regards

**Comment by ser-house** [comment]
@mdmrm Just call with 1:

bme280_init(1);

float temperature = bme280_readTemperature(1); // in °C
float pressure = bme280_readPressure(1) / 100.0; // in mbar
float humidity = bme280_readHumidity(1); // in %
